spring.application.name=api-product-service
server.port=9090

# =====================================================================
# MySQL DATABASE CONNECTION SETTINGS
# =====================================================================
# Replace 'localhost:3306' with your server host and 'your_database_name' with your actual schema
spring.datasource.url=jdbc:mysql://localhost:3306/product_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Database credentials
spring.datasource.username=root
spring.datasource.password=Param@123

# Driver class name (Optional for modern Spring Boot versions as it auto-detects it)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver